DROP TABLE IF EXISTS `#__paymybill`;
CREATE TABLE `#__paymybill` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `order_id` varchar(255) DEFAULT NULL,
  `product_name` varchar(255) DEFAULT NULL,
  `payment_title` varchar(255) DEFAULT NULL,
  `payment_method` varchar(255) DEFAULT NULL,
  `mode` varchar(255) DEFAULT NULL,
  `currency` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `payment` varchar(255) DEFAULT NULL,
  `subtotal` varchar(255) DEFAULT NULL,
  `trans_cost` varchar(255) DEFAULT NULL,
  `trans_percent_cost` varchar(255) DEFAULT NULL,
  `payment_type` varchar(255) DEFAULT NULL,
  `BillFname` varchar(255) DEFAULT NULL,
  `BillLname` varchar(255) DEFAULT NULL,
  `BillAddr` varchar(255) DEFAULT NULL,
  `BillCity` varchar(255) DEFAULT NULL,
  `BillZip` varchar(255) DEFAULT NULL,
  `BillState` varchar(255) DEFAULT NULL,
  `BillCountry` varchar(255) DEFAULT NULL,
  `BillEmail` varchar(255) DEFAULT NULL,
  `BillPhone` varchar(255) DEFAULT NULL,
  `InvNr` varchar(255) DEFAULT NULL,
  `license` varchar(255) DEFAULT NULL,
  `attachments` varchar(500) DEFAULT NULL,
  `cdate` int(11) DEFAULT '0',
  `mdate` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;